[package]
name = "panicmsg"
version = "1.0.5"
edition = "2021"
description = "A library for simplyifying common panic messages."
repository = "https://github.com/ErisianArchitect/panicmsg"
documentation = "https://docs.rs/panicmsg"
license = "MIT"